### ISSUE TITLE
Multiple error events on bad statement preparation

### ISSUE THREAD

**Issue by dhensby** [TimelordUK/node-sqlserver-v8#133]
Please see https://github.com/tediousjs/node-mssql/issues/973 for context.

It appears that attempting to prepare a bad statement results in two error events being emitted. For example `req.prepare('SELECT col FROM spt_monitor')` results in 2 errors being emitted:

- `[Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid object name 'missingtable'.`
- `[Microsoft][SQL Server Native Client 11.0][SQL Server]Statement(s) could not be prepared.`

This is problematic because this means it is difficult to know when the connection is going to stop throwing errors and when it is ready for re-use if we don't have a maximum of one error per request via the connection.

Is there something I'm missing that I could use to know if the errors were over or could work be done to make sure connections only emit one error?

**Comment by TimelordUK** [comment]
Do I not send a second parameter along with error on the emit saying if more errors will follow. This is done whilst reading results of a query it is possible your issue is raised from a different place.  If you look at stack from where you receive these multiple errors where is it coming from. If it’s reader.js this should provide a Boolean.

**Comment by dhensby** [comment]
Ah, I'll take a look into that; thanks.

**Comment by Doc999tor** [comment]
@dhensby Any updates with that?

**Comment by dhensby** [comment]
Yes, thanks. I'm trying to handle this here https://github.com/tediousjs/node-mssql/pull/981

So not an issue with this library, just our implementation.
