### ISSUE TITLE
gyp Error when installing msnodesqlv8@2.0.8 on Redhat Linux 7.6 

### ISSUE THREAD

**Issue by Shao-Eric** [TimelordUK/node-sqlserver-v8#191]
Hi,

I am getting the below error when installing msnodesqlv8 on Linux. Please advise if I am missing anything here.
(Node=14.9.0, NPM=6.14.8, Operating System: Red Hat Linux 7.6)

Thanks in advance

> prebuild-install || node-gyp rebuild

prebuild-install WARN install read ECONNRESET
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
gyp ERR! System Linux 3.10.0-957.21.2.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /project/node_modules/msnodesqlv8
gyp ERR! node -v v14.9.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN dbconnect@7.6.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! msnodesqlv8@2.0.8 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the msnodesqlv8@2.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/userId/.npm/_logs/2020-12-21T16_44_15_324Z-debug.log

Operating System:
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

**Comment by TimelordUK** [comment]
this is probably due to being behind a firewall - the npm installation includes a step to download the correct binary from 

https://github.com/TimelordUK/node-sqlserver-v8/releases/tag/v2.0.8

and the selected binary is unpacked and copied to the target build/Release/sqlserverv8.node 
this is a native binary loaded as a shared object and communicates with the javascript and odbc native library.

one option try and configure your proxy settings to allow the call to git over https

https://www.jhipster.tech/configuring-a-corporate-proxy/

or possibly run install and suppress the post install step and download and install the binary yourself e.g. from a browser 

lastly, if you have access to git you could install from master and build the code - this requires

git clone https://github.com/TimelordUK/node-sqlserver-v8.git node-modules/msnodesqlv8
npm install --g node-gyp
cd node-modules/msnodesqlv8
node-gyp rebuild

**Comment by Shao-Eric** [comment]
There was a firewall issue, Thanks!
