### ISSUE TITLE
Using stored procedures with a pool

### ISSUE THREAD

**Issue by CS-Jfilmer** [TimelordUK/node-sqlserver-v8#203]
Hia, from the docs and looking at the code it seems as though using stored procedures along with a connection pool is not supported.

I'm still a little new to MSSQL so I fear I may be missing some fundamental detail. Is there any reason you wouldn't want to use a connection pool for better performance even if you are using stored procs?

**Comment by TimelordUK** [comment]
hi,

there is an update in master not yet released still being tested where callproc  has been added to both the pool and a connection - the reason this has been tricky in this particular library is due to an early design decision where in effect each connection owns a cache of proc definitions and running in say a large pool of 10 or more would mean each connection in pool having to fetch meta data related to procedure.

The Pool itself now owns the master cache and each connection uses thus where any connection fetching a definition will mean all pool members are aware of it.

This will take quite a bit of testing before it is releaed - but can be checked out and used from master i.e. the test suite runs but is not yet completed.

```typescript
export interface Pool {
    open(): void
    close(cb: StatusCb): void
    query(sql: string, cb?: QueryCb): Query
    query(sql: string, params?: any[], cb?: QueryCb): Query
    query(description: QueryDescription, cb?: QueryCb): Query
    query(description: QueryDescription, params?: any[], cb?: QueryCb): Query
    queryRaw(description: QueryDescription, cb: QueryRawCb): Query
    queryRaw(description: QueryDescription, params?: any[], cb?: QueryRawCb): Query
    queryRaw(sql: string, params?: any[], cb?: QueryRawCb): Query
    queryRaw(sql: string, cb: QueryRawCb): Query
    callproc(name: string, params?: any[], cb?: CallProcedureCb): Query
}
```

![image](https://user-images.githubusercontent.com/7300251/114304805-12d73900-9acd-11eb-8a18-a42ab373fd87.png)

**Comment by CS-Jfilmer** [comment]
Awesome thanks so much for the reply. We'll wait for the tests 😄
