### ISSUE TITLE
Package not working on Node 16

### ISSUE THREAD

**Issue by williamhu99** [TimelordUK/node-sqlserver-v8#266]
👋 I'm trying to use the `msnodesqlv8` package on Node 16, but I keep getting segmentation faults. When I upgrade to Node 18 with `nvm use 18`, however, I'm able to use the package successfully. Any reason why this would be the case?

**Comment by TimelordUK** [comment]
if you look over closed issues its probably related to this

https://github.com/TimelordUK/node-sqlserver-v8/issues/168

which is openssl and the version running - there is not much that can be done save for installing say openbrew version and using LD_LIBRARY_PATH

```txt
me:~/dev/js/v8/node_modules/msnodesqlv8$ node_modules/.bin/mocha test/prepared.js


  prepared
Segmentation fault
me~/dev/js/v8/node_modules/msnodesqlv8$ !704
export LD_PRELOAD=~/libssl.so.1.1
me:~/dev/js/v8/node_modules/msnodesqlv8$ node_modules/.bin/mocha test/prepared.js


  prepared
    ✔ use prepared and select nvarchar max with max default size on connection (41ms)
me:~/dev/js/v8/node_modules/msnodesqlv8$
```

**Comment by TimelordUK** [comment]
```sh
/libssl.so.1.1 -> /home/linuxbrew/.linuxbrew/opt/openssl@3/lib/libssl.so.3
```

**Comment by williamhu99** [comment]
Thank you for the fast response! I was using that issue to debug earlier, but I wasn't able to get anything working even with `export LD_PRELOAD=~/libssl.so.1.1`.  I've tried symlinking `libssl.so.3` as `libssl.so.1.1` in both `/usr/lib/` and `node_modules/msnodesqlv8`, and I've tried directly downloading `libssl.so.1.1`. Both have not resolved the issue 😔

**Comment by TimelordUK** [comment]
https://github.com/TimelordUK/node-sqlserver-v8/issues/223

Have you run node via gdb such as above and got a full stack trace.  If seg fault is indeed in OpenSSL then it must be the case the wrong version is being loaded. 

This can be very confusing I myself have sometimes struggled to find where it is being loaded from. The OpenSSL is dynamically loaded by the ms native driver. If all else fails it may be possible to hard link the library by rebuilding the cpp on target machine and add the ssl into dependencies.  At least this will prove the issue.

I never see this on macos. The problem is really down to the nature of dynamically loading the library

**Comment by williamhu99** [comment]
I'm still running into this problem, but I'm going to close the issue for now since I'm no longer actively working on it. Thank you for the help though :)
